# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8ea521129d875a69197ab4def6db2420d6d22f5d8cd91a6e87d74165b6033a3e7f436a23d62923fa3e1e977c14440ebb4b14d24d38eacb0c11985946dded7f2

test:
  secret_key_base: a947ef9500d106bb171229e2eb25161d9e09068b69b6a894e39c2c0fd4164217ceec784387a0fce8673c37328f4124ec0ad76daa886146032453c2fef26cb84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
